name: CI/CD
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
    

jobs:
  tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout code
        uses: actions/setup-node@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-versions: 18.v
      - name: Install dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli
      - name: Build Angular App
        run: ng build
      - name: Run tests with code coverage
        uses: coactions/setup-xvfb@v1
        with: 
          run: npm run test -- --no-watch --code-coverage
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}

